name: edgespace_ai
description: EdgeSpace AI - Smart Spaces / IoT monitoring, analytics, ESP32-C3 onboarding and AI-assisted decision support.
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.4.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # State management
  provider: ^6.1.2

  # Charts / Analytics
  fl_chart: ^0.69.0

  # Bluetooth Low Energy
  flutter_blue_plus: ^1.34.5

  # Android runtime permissions
  permission_handler: ^12.0.1

  # QR scanning
  mobile_scanner: ^7.4.0

  # HTTP / AI API / Backend
  http: ^1.2.2

  # Local storage
  shared_preferences: ^2.3.2

  # Formatting
  intl: ^0.19.0

  # IDs
  uuid: ^4.5.1
  firebase_core: ^4.14.0
  firebase_auth: ^6.6.1
  google_sign_in: ^7.2.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^4.0.0

flutter:
  uses-material-design: true